image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      source ~/.bashrc && source ~/.ghcup/env
      cabal update
      stack build --system-ghc
  - name: nvim
    command: |
      source ~/.bashrc && source ~/.ghcup/env
      nvim --headless +PlugInstall +qall
  - name: git
    command: |
      git config --global commit.gpgsign true
      git config --global gpg.program /usr/bin/krgpg
      cd /workspace/natskell && git config remote.origin.url git@github.com:samisagit/natskell.git
github:
  prebuilds:
    master: true
    branches: true
