name: Main Merge

on:
  merge_group:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: samisagit-natskell
    - run: nix develop --command bash -c "make build-test"
    - run: nix develop --command bash -c "make lint"
  cabal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: samisagit-natskell
    - run: nix develop --command bash -c "cabal check"
  test-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: samisagit-natskell
    - run: nix develop --command bash -c "make build-test"
    - run: nix develop --command bash -c "make test-all"
