name: Package

on:
  workflow_call:

permissions:
  contents: read

jobs:
  package:
    name: package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build source distribution
      run: nix build .#sdist --out-link result-sdist
    - name: Upload source distribution artifact
      uses: actions/upload-artifact@v7
      with:
        name: natskell-sdist
        path: 'result-sdist/*.tar.gz'
        if-no-files-found: error
    - name: Build Hackage documentation
      run: nix build .#hackage-docs --out-link result-hackage-docs
    - name: Upload Hackage documentation artifact
      uses: actions/upload-artifact@v7
      with:
        name: natskell-hackage-docs
        path: 'result-hackage-docs/*-docs.tar.gz'
        if-no-files-found: error
